# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-25 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_time',
            field=models.CharField(max_length=200, verbose_name='上映时间'),
        ),
    ]
