# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-31 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20181025_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='视频名称'),
        ),
    ]
